// Command genspec transpiles the committed TypeScript metadata (the
// hl7/metadata segment and data-type catalogs) into committed Go (*_gen.go)
// under client/hl7. The HL7 value tables are generated separately by
// cmd/gentables. genspec makes no network calls: it
// reads the vendored *.ts files and reproduces the catalog exactly, so end
// users ship a fixed catalog.
//
// Usage:
//
//	go run ./cmd/genspec -src <src/hl7> -out <client/hl7>
//
// The -src flag is required and points at the vendored hl7/ source tree; -out
// defaults to the committed output tree under client/hl7.
package main

/*
MIT License

Copyright (c) 2026 Shane

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const genBanner = "// Code generated by genspec; DO NOT EDIT.\n"

func main() {
	srcDir := flag.String("src", "",
		"path to the vendored hl7/ source tree (required)")
	outDir := flag.String("out", "client/hl7",
		"path to the committed Go output tree (client/hl7)")
	flag.Parse()

	if *srcDir == "" {
		fmt.Fprintln(os.Stderr, "the -src flag is required: pass the path to the vendored hl7/ source tree")
		os.Exit(1)
	}

	if err := run(*srcDir, *outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(srcDir, outDir string) error {
	if err := genSegments(srcDir, outDir); err != nil {
		return err
	}
	if err := genDataTypes(srcDir, outDir); err != nil {
		return err
	}
	// The HL7 value tables (tables/tables_gen.go) are owned by cmd/gentables,
	// which builds the full per-version registry from the Caristix API. genspec
	// no longer emits them.
	return nil
}

// writeGo gofmts the source and writes it to path.
func writeGo(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("genspec: gofmt %s: %w\n----\n%s", path, err, src)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

// genSegments parses metadata/segments/index.ts for the SEGMENT_SPECS map (key
// order and per-key SPEC const), reads each per-segment *.ts file for its
// SegmentSpec literal, and writes segments_gen.go.
func genSegments(srcDir, outDir string) error {
	segDir := filepath.Join(srcDir, "metadata", "segments")
	indexSrc, err := os.ReadFile(filepath.Join(segDir, "index.ts"))
	if err != nil {
		return err
	}
	// Parse the SEGMENT_SPECS object literal: key -> SPEC_CONST identifier.
	entries, err := parseSpecMap(string(indexSrc), "SEGMENT_SPECS")
	if err != nil {
		return err
	}

	// Map each SPEC_CONST to the segment file holding it. The file basename is
	// the lowercase of the const minus the _SPEC suffix (ZL7_SPEC -> zl7.ts).
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("\npackage metadata\n\n")
	b.WriteString("// SegmentSpecs is the generated registry of HL7 segment specs, mirroring\n")
	b.WriteString("// the SEGMENT_SPECS aggregation. Keys are segment names as the spec keys\n")
	b.WriteString("// them (e.g. \"Zxx\"). It drives the spec-driven builder's per-version usage\n")
	b.WriteString("// validation.\n")
	b.WriteString("var SegmentSpecs = map[string]SegmentSpec{\n")
	for _, e := range entries {
		fileBase := strings.ToLower(strings.TrimSuffix(e.constName, "_SPEC"))
		fileSrc, err := os.ReadFile(filepath.Join(segDir, fileBase+".ts"))
		if err != nil {
			return fmt.Errorf("genspec: segment %s: %w", e.key, err)
		}
		_, val, err := parseExportConst(string(fileSrc))
		if err != nil {
			return fmt.Errorf("genspec: segment %s: %w", e.key, err)
		}
		obj, ok := val.(map[string]jsValue)
		if !ok {
			return fmt.Errorf("genspec: segment %s: spec is not an object", e.key)
		}
		fmt.Fprintf(&b, "\t%q: ", e.key)
		writeSegmentSpec(&b, obj)
		b.WriteString(",\n")
	}
	b.WriteString("}\n")

	return writeGo(filepath.Join(outDir, "metadata", "segments_gen.go"), b.String())
}

func writeSegmentSpec(b *strings.Builder, obj map[string]jsValue) {
	b.WriteString("{\n")
	fmt.Fprintf(b, "Name: %q,\n", asString(obj["name"]))
	fmt.Fprintf(b, "Description: %q,\n", asString(obj["description"]))
	// Versions.
	b.WriteString("Versions: []HL7Version{")
	if vers, ok := obj["versions"].([]jsValue); ok {
		for i, v := range vers {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%q", asString(v))
		}
	}
	b.WriteString("},\n")
	// Fields.
	b.WriteString("Fields: []FieldSpec{\n")
	if fields, ok := obj["fields"].([]jsValue); ok {
		for _, f := range fields {
			fo, _ := f.(map[string]jsValue)
			writeFieldSpec(b, fo)
		}
	}
	b.WriteString("},\n")
	b.WriteString("}")
}

func writeFieldSpec(b *strings.Builder, f map[string]jsValue) {
	b.WriteString("{\n")
	fmt.Fprintf(b, "Num: %d,\n", asInt(f["num"]))
	fmt.Fprintf(b, "Name: %q,\n", asString(f["name"]))
	if t := asString(f["hl7Type"]); t != "" {
		fmt.Fprintf(b, "HL7Type: %q,\n", t)
	}
	writeLength(b, f["length"])
	if tbl, ok := f["table"]; ok && tbl != nil {
		fmt.Fprintf(b, "Table: %d,\n", asInt(tbl))
	}
	writeComponents(b, f["components"])
	// Usage map (per-version).
	b.WriteString("Usage: map[HL7Version]HL7UsageCode{")
	if usage, ok := f["usage"].(map[string]jsValue); ok {
		keys := sortedKeys(usage)
		for _, k := range keys {
			fmt.Fprintf(b, "%q: %q, ", k, asString(usage[k]))
		}
	}
	b.WriteString("},\n")
	b.WriteString("},\n")
}

func writeComponents(b *strings.Builder, v jsValue) {
	comps, ok := v.([]jsValue)
	if !ok || len(comps) == 0 {
		return
	}
	b.WriteString("Components: []ComponentSpec{\n")
	for _, c := range comps {
		co, _ := c.(map[string]jsValue)
		writeComponentSpec(b, co)
	}
	b.WriteString("},\n")
}

func writeComponentSpec(b *strings.Builder, c map[string]jsValue) {
	b.WriteString("{")
	fmt.Fprintf(b, "Num: %d, ", asInt(c["num"]))
	fmt.Fprintf(b, "Name: %q, ", asString(c["name"]))
	if t := asString(c["hl7Type"]); t != "" {
		fmt.Fprintf(b, "HL7Type: %q, ", t)
	}
	writeLengthInline(b, c["length"])
	if tbl, ok := c["table"]; ok && tbl != nil {
		fmt.Fprintf(b, "Table: %d, ", asInt(tbl))
	}
	if r := asString(c["rpt"]); r != "" {
		fmt.Fprintf(b, "Rpt: %q, ", r)
	}
	if u := asString(c["usage"]); u != "" {
		fmt.Fprintf(b, "Usage: %q, ", u)
	}
	b.WriteString("},\n")
}

// writeLength emits a Length literal for a field (multi-line context). The
// committed catalog only ever uses the { max: N } form, so Exact/Min stay zero.
func writeLength(b *strings.Builder, v jsValue) {
	max, set := lengthMax(v)
	if !set {
		return
	}
	fmt.Fprintf(b, "Length: Length{Max: %d, Set: true},\n", max)
}

func writeLengthInline(b *strings.Builder, v jsValue) {
	max, set := lengthMax(v)
	if !set {
		return
	}
	fmt.Fprintf(b, "Length: Length{Max: %d, Set: true}, ", max)
}

func lengthMax(v jsValue) (int, bool) {
	obj, ok := v.(map[string]jsValue)
	if !ok {
		return 0, false
	}
	mv, ok := obj["max"]
	if !ok || mv == nil {
		return 0, false
	}
	return asInt(mv), true
}

// genDataTypes parses metadata/datatypes/index.ts for the DATA_TYPES map and
// writes datatypes_gen.go.
func genDataTypes(srcDir, outDir string) error {
	idxPath := filepath.Join(srcDir, "metadata", "datatypes", "index.ts")
	src, err := os.ReadFile(idxPath)
	if err != nil {
		return err
	}
	dt, err := parseObjectConst(string(src), "DATA_TYPES")
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("\npackage metadata\n\n")
	b.WriteString("// DataTypes is the generated registry of composite HL7 data-type component\n")
	b.WriteString("// layouts (XAD, XPN, CE, CWE, CX, ...), mirroring the DATA_TYPES. The\n")
	b.WriteString("// builder assembles composite-object field inputs from these component lists.\n")
	b.WriteString("var DataTypes = map[string][]ComponentSpec{\n")
	for _, name := range sortedKeys(dt) {
		comps, _ := dt[name].([]jsValue)
		fmt.Fprintf(&b, "\t%q: {\n", name)
		for _, c := range comps {
			co, _ := c.(map[string]jsValue)
			writeComponentSpec(&b, co)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	return writeGo(filepath.Join(outDir, "metadata", "datatypes_gen.go"), b.String())
}

// helpers ------------------------------------------------------------------

func asString(v jsValue) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}

func asInt(v jsValue) int {
	if f, ok := v.(float64); ok {
		return int(f)
	}
	return 0
}

func sortedKeys(m map[string]jsValue) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

type specMapEntry struct {
	key       string
	constName string
}

// parseSpecMap extracts the `export const NAME: ... = { KEY: CONST, ... }`
// mapping, preserving source order, where each value is a bare identifier
// (the per-segment SPEC const). It scans the literal text directly because the
// values are identifiers, not literals the JS parser resolves.
func parseSpecMap(src, name string) ([]specMapEntry, error) {
	marker := "export const " + name
	idx := strings.Index(src, marker)
	if idx < 0 {
		return nil, fmt.Errorf("genspec: %s not found", name)
	}
	open := strings.Index(src[idx:], "{")
	if open < 0 {
		return nil, fmt.Errorf("genspec: %s has no body", name)
	}
	p := newJSParser(src[idx+open:])
	val, err := p.parseValue()
	if err != nil {
		return nil, err
	}
	obj, ok := val.(map[string]jsValue)
	if !ok {
		return nil, fmt.Errorf("genspec: %s is not an object", name)
	}
	// parseValue loses source order; recover order by scanning keys in text.
	entries := make([]specMapEntry, 0, len(obj))
	body := src[idx+open : idx+open+p.pos]
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		colon := strings.Index(line, ":")
		if colon <= 0 {
			continue
		}
		key := strings.TrimSpace(line[:colon])
		if c, ok := obj[key]; ok {
			cn, _ := c.(string)
			entries = append(entries, specMapEntry{key: key, constName: cn})
			delete(obj, key)
		}
	}
	return entries, nil
}

// parseObjectConst extracts `export const NAME ... = { ... }` and returns the
// parsed object.
func parseObjectConst(src, name string) (map[string]jsValue, error) {
	marker := "export const " + name
	idx := strings.Index(src, marker)
	if idx < 0 {
		return nil, fmt.Errorf("genspec: %s not found", name)
	}
	open := strings.Index(src[idx:], "{")
	if open < 0 {
		return nil, fmt.Errorf("genspec: %s has no body", name)
	}
	p := newJSParser(src[idx+open:])
	val, err := p.parseValue()
	if err != nil {
		return nil, err
	}
	obj, ok := val.(map[string]jsValue)
	if !ok {
		return nil, fmt.Errorf("genspec: %s is not an object", name)
	}
	return obj, nil
}
