// MIT License
//
// Copyright (c) 2026 Shane
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

// Command gentables builds the per-version HL7 value-table registry from the
// Caristix HL7 Definition API and writes client/hl7/tables/tables_gen.go.
//
// The raw Caristix JSON is vendored in-repo under cmd/gentables/caristix so a
// regeneration is reproducible offline: vendored JSON is preferred and the
// network is only hit to (re)fill a missing file. The generated Go library
// makes ZERO runtime network calls; only this generator touches the network.
//
// Usage:
//
//	go run ./cmd/gentables            # use vendored JSON, fetch what is missing
//	go run ./cmd/gentables -refresh   # re-fetch every table detail from the API
//
// The output is keyed version -> table id -> ordered code list. Only tables
// whose detail carries a non-empty entries array are emitted (a fixed value
// set to enforce); user-defined tables with no entries are skipped.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"math/rand"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

// versions are node-hl7's VERSIONS, in the Caristix path spelling.
var versions = []string{"2.1", "2.2", "2.3", "2.3.1", "2.4", "2.5", "2.5.1", "2.6", "2.7", "2.7.1", "2.8"}

const (
	apiBase     = "https://hl7-definition.caristix.com/v2-api/1"
	concurrency = 16
	maxRetries  = 6
)

const mitHeader = `// MIT License
//
// Copyright (c) 2026 Shane
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
`

const genBanner = "// Code generated by gentables; DO NOT EDIT.\n"

// tableListItem is one entry in the per-version Tables list response.
type tableListItem struct {
	ID    string `json:"id"`
	Type  string `json:"type"`
	Label string `json:"label"`
}

// tableEntry is one code in a table detail's entries array.
type tableEntry struct {
	Value       string `json:"value"`
	Description string `json:"description"`
	Comment     string `json:"comment"`
}

// tableDetail is the per-table detail response.
type tableDetail struct {
	ID        string       `json:"id"`
	TableID   string       `json:"tableId"`
	TableType string       `json:"tableType"`
	Name      string       `json:"name"`
	Entries   []tableEntry `json:"entries"`
}

func main() {
	var (
		outDir    string
		vendorDir string
		refresh   bool
	)
	flag.StringVar(&outDir, "out", "client/hl7", "output tree root (writes tables/tables_gen.go under it)")
	flag.StringVar(&vendorDir, "vendor", "cmd/gentables/caristix", "vendored Caristix JSON tree")
	flag.BoolVar(&refresh, "refresh", false, "re-fetch every table detail from the network even if vendored")
	flag.Parse()

	if err := run(outDir, vendorDir, refresh); err != nil {
		fmt.Fprintln(os.Stderr, "gentables:", err)
		os.Exit(1)
	}
}

func run(outDir, vendorDir string, refresh bool) error {
	client := &http.Client{Timeout: 60 * time.Second}

	// version -> table id -> ordered codes
	out := map[string]map[string][]string{}

	for _, ver := range versions {
		list, err := fetchList(client, vendorDir, ver, refresh)
		if err != nil {
			return fmt.Errorf("version %s list: %w", ver, err)
		}

		details, err := fetchDetails(client, vendorDir, ver, list, refresh)
		if err != nil {
			return fmt.Errorf("version %s details: %w", ver, err)
		}

		verTables := map[string][]string{}
		for id, d := range details {
			if len(d.Entries) == 0 {
				continue // nothing to enforce
			}
			codes := make([]string, len(d.Entries))
			for i, e := range d.Entries {
				codes[i] = e.Value
			}
			verTables[id] = codes
		}
		out[ver] = verTables
		fmt.Fprintf(os.Stderr, "gentables: v%s -> %d tables with values (of %d listed)\n", ver, len(verTables), len(list))
	}

	return writeTables(outDir, out)
}

// fetchList returns the Tables list for a version, preferring the vendored
// _list.json and only hitting the network when it is missing or -refresh is set.
func fetchList(client *http.Client, vendorDir, ver string, refresh bool) ([]tableListItem, error) {
	path := filepath.Join(vendorDir, "HL7v"+ver, "_list.json")
	if !refresh {
		if data, err := os.ReadFile(path); err == nil {
			var list []tableListItem
			if err := json.Unmarshal(data, &list); err == nil && len(list) > 0 {
				return list, nil
			}
		}
	}

	url := fmt.Sprintf("%s/HL7v%s/Tables", apiBase, ver)
	data, err := get(client, url)
	if err != nil {
		return nil, err
	}
	var list []tableListItem
	if err := json.Unmarshal(data, &list); err != nil {
		return nil, fmt.Errorf("decode list: %w", err)
	}
	if err := writeVendor(path, data); err != nil {
		return nil, err
	}
	return list, nil
}

// fetchDetails fetches each table detail for a version with bounded
// concurrency, preferring vendored JSON. It returns id -> detail.
func fetchDetails(client *http.Client, vendorDir, ver string, list []tableListItem, refresh bool) (map[string]tableDetail, error) {
	type result struct {
		id     string
		detail tableDetail
		err    error
	}

	sem := make(chan struct{}, concurrency)
	results := make(chan result, len(list))
	var wg sync.WaitGroup

	for _, item := range list {
		// Only HL7 value tables carry a code set; skip user/name lists by type
		// is not reliable, so we fetch all and filter on empty entries later.
		wg.Add(1)
		go func(id string) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			d, err := fetchDetail(client, vendorDir, ver, id, refresh)
			results <- result{id: id, detail: d, err: err}
		}(item.ID)
	}

	go func() {
		wg.Wait()
		close(results)
	}()

	out := map[string]tableDetail{}
	for r := range results {
		if r.err != nil {
			return nil, fmt.Errorf("table %s: %w", r.id, r.err)
		}
		out[r.id] = r.detail
	}
	return out, nil
}

// fetchDetail returns one table detail, preferring the vendored JSON.
func fetchDetail(client *http.Client, vendorDir, ver, id string, refresh bool) (tableDetail, error) {
	path := filepath.Join(vendorDir, "HL7v"+ver, id+".json")
	if !refresh {
		if data, err := os.ReadFile(path); err == nil {
			var d tableDetail
			if err := json.Unmarshal(data, &d); err == nil {
				return d, nil
			}
		}
	}

	url := fmt.Sprintf("%s/HL7v%s/Tables/%s", apiBase, ver, id)
	data, err := get(client, url)
	if err != nil {
		return tableDetail{}, err
	}
	var d tableDetail
	if err := json.Unmarshal(data, &d); err != nil {
		return tableDetail{}, fmt.Errorf("decode detail: %w", err)
	}
	if err := writeVendor(path, data); err != nil {
		return tableDetail{}, err
	}
	return d, nil
}

// get does a polite GET with retry/backoff for rate limiting and transient
// failures.
func get(client *http.Client, url string) ([]byte, error) {
	var lastErr error
	for attempt := 0; attempt < maxRetries; attempt++ {
		if attempt > 0 {
			// exponential backoff with jitter
			base := time.Duration(1<<uint(attempt-1)) * 500 * time.Millisecond
			jitter := time.Duration(rand.Int63n(int64(250 * time.Millisecond)))
			time.Sleep(base + jitter)
		}
		req, err := http.NewRequest(http.MethodGet, url, nil)
		if err != nil {
			return nil, err
		}
		req.Header.Set("accept", "application/json")
		resp, err := client.Do(req)
		if err != nil {
			lastErr = err
			continue
		}
		body, readErr := io.ReadAll(resp.Body)
		_ = resp.Body.Close()
		if resp.StatusCode == http.StatusTooManyRequests || resp.StatusCode >= 500 {
			lastErr = fmt.Errorf("status %d", resp.StatusCode)
			continue
		}
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("status %d for %s", resp.StatusCode, url)
		}
		if readErr != nil {
			lastErr = readErr
			continue
		}
		return body, nil
	}
	return nil, fmt.Errorf("get %s: %w", url, lastErr)
}

// writeVendor stores the raw JSON under the vendored tree, pretty-printed so the
// committed diff stays reviewable.
func writeVendor(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var pretty bytes.Buffer
	if err := json.Indent(&pretty, data, "", "  "); err != nil {
		// Fall back to the raw bytes if it is not valid JSON for some reason.
		return os.WriteFile(path, data, 0o644)
	}
	pretty.WriteByte('\n')
	return os.WriteFile(path, pretty.Bytes(), 0o644)
}

// writeTables emits the per-version tables_gen.go.
func writeTables(outDir string, out map[string]map[string][]string) error {
	var b strings.Builder
	b.WriteString(mitHeader)
	b.WriteString(genBanner)
	b.WriteString("\npackage tables\n\n")
	b.WriteString("// TABLES is the generated registry of HL7 value tables, keyed by HL7\n")
	b.WriteString("// version (\"2.8\") then numeric table id (\"0001\") to the ordered code list.\n")
	b.WriteString("// HL7 table values differ by version, so enforcement stays version-aware.\n")
	b.WriteString("// Only tables that carry a fixed value set are present; FieldSpec.Table and\n")
	b.WriteString("// ComponentSpec.Table reference an entry here for hard-error enum validation.\n")
	b.WriteString("var TABLES = map[string]map[string][]string{\n")

	for _, ver := range versions {
		verTables := out[ver]
		ids := make([]string, 0, len(verTables))
		for id := range verTables {
			ids = append(ids, id)
		}
		sort.Strings(ids)

		fmt.Fprintf(&b, "\t%q: {\n", ver)
		for _, id := range ids {
			fmt.Fprintf(&b, "\t\t%q: {", id)
			for i, v := range verTables[id] {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%q", v)
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	path := filepath.Join(outDir, "tables", "tables_gen.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}
